[package]
name = "china-dictatorship"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/cirosantilli/china-dictatorship"
include = [
    "**/*.rs",
    "Cargo.toml",
    "Cargo.lock",
    "README.md",
]
[dependencies]

